version: "3.8"
services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - localnet

  app:
    build: .
    command: npm start
    environment:
      DATABASE_URL: postgres://myuser:mypass@db:5432/mydb
      PORT: 8080
    depends_on:
      - db
    networks:
      - localnet

volumes:
  pgdata:

networks:
  localnet:
