name: CI/CD → Cloud Run

on:
  push:
    branches: [ "main" ]

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      # Authenticate to Google Cloud using service account key
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up gcloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          install_components: "gke-gcloud-auth-plugin"

      - name: Build and Push Docker Image
        run: |
          IMAGE="gcr.io/${{ secrets.GCP_PROJECT }}/tiny-cloudrun-app:${{ github.sha }}"
          docker build -t "$IMAGE" .
          echo "$IMAGE" > image_ref.txt
          docker push "$IMAGE"

      - name: Deploy to Cloud Run (no traffic)
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: tiny-cloudrun-app
          image: "gcr.io/${{ secrets.GCP_PROJECT }}/tiny-cloudrun-app:${{ github.sha }}"
          region: us-central1
          allow_unauthenticated: true
          no_traffic: true
          env_vars: VERSION=${{ github.sha }}
