name: CI/CD → Cloud Run

on:
  push:
    branches: [ "main" ]

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      # Authenticate to Google Cloud using service account key
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up gcloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: playground-s-11-18c7261a
          install_components: "gke-gcloud-auth-plugin"

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker gcr.io --quiet

      - name: Build and Push Docker Image
        run: |
          IMAGE="gcr.io/playground-s-11-18c7261a/tiny-cloudrun-app:${GITHUB_SHA}"
          docker build -t "$IMAGE" .
          echo "$IMAGE" > image_ref.txt
          docker push "$IMAGE"

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy tiny-cloudrun-app \
            --image=gcr.io/playground-s-11-18c7261a/tiny-cloudrun-app:${GITHUB_SHA} \
            --region=us-central1 \
            --allow-unauthenticated \
            --platform=managed \
            --concurrency=80 \
            --min-instances=0 \
            --max-instances=5 \
            --set-env-vars VERSION=${GITHUB_SHA}
